### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
See https://github.com/Particular/Particular.Approvals/pull/153

**Comment by DavidBoike** [comment]
NServiceBus 7 release branches still target net452, but test projects appear to still be a mishmash in those branches. Just in the Core/release-7.7 I found most test projects were net452, though some of the persistence test projects are net461 (created later?) and Analyzer tests are net472 (but that's different).

But Dependabot doesn't target release branches anyway. Why can't release branches stay on older versions?

@bording will be back on Monday.

**Comment by danielmarbach** [comment]
> Why can't release branches stay on older versions?

My thinking was they should stay on an older version and that's totally ok. My preference would be to go with 

https://github.com/Particular/Particular.Approvals/pull/153

**Comment by bording** [comment]
> My thinking was they should stay on an older version and that's totally ok. My preference would be to go with

Yes, I think it would be fine to keep the release branches on the older version, especially if there's  a chance that moving to System.Text.Json would result in a change in the appproval files.

Based on that, I think it's fine to move to System.Text.Json. We should close this and got with #153 instead.

**Pull request closed without merging**
